const functions = require("firebase-functions");
// const fetch = require("node-fetch"); // Native fetch is available in Node 18+

exports.polishContent = functions.https.onCall(async (data, context) => {
  try {
    // Check if user is authenticated (optional but recommended)
    // if (!context.auth) {
    //   throw new functions.https.HttpsError('unauthenticated', 'The function must be called while authenticated.');
    // }

    const prompt = data.prompt;
    if (!prompt) {
      throw new functions.https.HttpsError('invalid-argument', 'The function must be called with a "prompt" argument.');
    }

    // Get API key from environment config
    const config = functions.config();
    if (!config.gemini || !config.gemini.key) {
        console.error("Configuration Error: gemini.key is missing.");
        throw new functions.https.HttpsError('internal', 'Server configuration error: API key missing.');
    }
    
    const apiKey = config.gemini.key;
    console.log("Debug: API Key present.");

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

    const payload = {
      contents: [{
        parts: [{
          text: prompt
        }]
      }]
    };

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
        const errorText = await response.text();
        console.error("Gemini API Error:", response.status, errorText);
        throw new functions.https.HttpsError('internal', `Gemini API failed: ${response.statusText} - ${errorText}`);
    }

    const responseData = await response.json();
    
    if (responseData.candidates && responseData.candidates.length > 0 && responseData.candidates[0].content) {
        return {
            text: responseData.candidates[0].content.parts[0].text.trim()
        };
    } else {
        throw new functions.https.HttpsError('internal', 'No content generated by Gemini.');
    }

  } catch (error) {
    console.error("Global Function Error:", error);
    // Re-throw HttpsErrors as is
    if (error.code && error.details) {
        throw error;
    }
    throw new functions.https.HttpsError('internal', `Internal Error: ${error.message}`);
  }
});
